# Travis CI integration -- https://travis-ci.org/troglobit/libuev
# Defaults to GNU GCC and autotools: ./configure && make && make test
language: c

# Use docker for quicker builds, it now allows https://docs.travis-ci.com/user/apt/
sudo: false

# Test build with both GCC and Clang (LLVM)
compiler:
  - gcc
  - clang

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "ikQcWMCLFoxq0+wMiqrNT5HRn0d4e3AxuF8VzNUNFrk6jUvHIufC/OKvr8VWPTjCaAQXZjWfdQAAARUXzJV10WZ7xpiv5qt4bt26Qih2AwMPMJeUOYrqXgQqhTPBp05iLYpo4ybICteXRI3zKKUA1wkdDC0jyu3rl+Fbveekbe0="

addons:
  apt:
    packages:
      - tree
      - doxygen
  coverity_scan:
    project:
      name: "troglobit/libuev"
      description: "libuEv | Simple event loop for Linux"
    notification_email: troglobit@gmail.com
    build_command_prepend: "./autogen.sh && ./configure --enable-examples"
    build_command: "make clean all"
    branch_pattern: dev

script:
  - ./autogen.sh
  - ./configure --prefix= --disable-silent-rules --enable-examples
  - make clean
  - make -j5
  - make check
  - DESTDIR=/tmp/tok make install-strip
  - tree /tmp/tok
